## **torch 基础**



In [2]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 按维度求和，keepdim控制是否保持维度不变
res1 = x.sum(dim=1, keepdim=False)
res2 = x.sum(dim=1, keepdim=True)

print(res1)
print(res2)

tensor([ 6, 15, 24])
tensor([[ 6],
        [15],
        [24]])


In [ ]:
a = torch.tensor([[1, 2, 3], 
                  [1, 2, 3]])

b = torch.tensor([[4, 5, 6], 
                  [4, 5, 6]])

# 按维度拼接张量
res = torch.cat([a, b], dim=1)
print(res)

tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
