## **torch 基础**



In [2]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 按维度求和，keepdim控制是否保持维度不变
res1 = x.sum(dim=1, keepdim=False)
res2 = x.sum(dim=1, keepdim=True)

print(res1)
print(res2)

e:\Python\py\envs\pytorch\lib\site-packages\torch\cuda\__init__.py:51: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


tensor([ 6, 15, 24])
tensor([[ 6],
        [15],
        [24]])


In [3]:
a = torch.tensor([[1, 2, 3], 
                  [1, 2, 3]])

b = torch.tensor([[4, 5, 6], 
                  [4, 5, 6]])

# 按维度拼接张量
res = torch.cat([a, b], dim=1)
print(res)

tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])


In [6]:
x = torch.ones((2, 2), dtype=torch.float)
x

tensor([[1., 1.],
        [1., 1.]])

`F.one_hot`的用法

In [ ]:
# 创建onehot向量

import torch.nn.functional as F
x = torch.tensor([1, 2, 3])
res = F.one_hot(x, 11)
res

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

`torch.arange(idx)` : 从0到idx-1生成一维向量

In [13]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`torch.gather` 和 `torch.where`

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7])
other = torch.tensor([-1, -1, -1, -1, -1, -1, -1])
idx = torch.tensor([0, 2, 3])
condition = torch.tensor([True, False, True, False, True, False, True])

# 按照idx索引取张量x中的值
res1 = torch.gather(x, dim=0, index=idx)

# 按条件取值，若满足则取x中的，不满足则取other中的
res2 = torch.where(condition, x, other)
print(res1)
print(res2)

tensor([1, 3, 4])
tensor([ 1, -1,  3, -1,  5, -1,  7])


根据索引取张量中的值

In [20]:
x = torch.tensor([1, 2, 3, 4, 5])
mask = [0, 1, 4]
x[mask]

tensor([1, 2, 5])

返回0 ~ n-1随机排列组合后的数

In [8]:
import torch
n = 10
torch.randperm(n)

tensor([7, 4, 5, 6, 2, 8, 3, 9, 0, 1])

`nn.Parameter()` : 将一个普通的张量（Tensor）“包装”起来，使其成为一个可训练的参数。

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# 实现一个简单线性层，而不用nn.Linear
class MyLinear(nn.Module):

    def __init__(self, input_features, output_features):
        super().__init__()
        # 使用nn.Parameter()包装后，self.weights 就会被 model.parameters() 包含，即从普通张量变为可训练参数
        self.weights = nn.Parameter(torch.randn(output_features, input_features))
        self.bias = nn.Parameter(torch.zeros(output_features))

    def forward(self, x):
        # 使用torch.mm实现矩阵乘法
        return torch.mm(x, self.weights.T) + self.bias
        
myLinear = MyLinear(10, 5)
for name, param in myLinear.named_parameters():
    print(f"{name}: {param.shape}")


weights: torch.Size([5, 10])
bias: torch.Size([5])


tensor([[ 2.0912,  0.0449, -5.2684, -2.9442,  2.7670],
        [ 0.4971, -0.2069, -0.4201, -3.4060,  3.6804]], grad_fn=<AddBackward0>)

`nn.Identity()` : 一个占位符算子, 相当于恒等映射 f(x) = x

In [27]:
import torch
import torch.nn as nn
import torchvision.models as models

# 一种用法：在迁移学习中提取特征
# 将其替换掉预训练好的分类模型的分类层即可

resnet18 = models.resnet18(pretrained=True)
print(f"原始resnet18.fc: {resnet18.fc}")
resnet18.fc = nn.Identity()
dummy_input = torch.randn((1, 3, 224, 224))
features = resnet18(dummy_input)
print(f"替换后模型输出为: {features.shape}(实际上是原本全连接层的输入)")

原始resnet18.fc: Linear(in_features=512, out_features=1000, bias=True)
替换后模型输出为: torch.Size([1, 512])(实际上是原本全连接层的输入)


`torch.randn(n)` : 生成服从标准正态分布的随机张量

In [18]:
torch.randn(5, 5)

tensor([[ 0.9293,  0.8916, -0.6318,  1.0930, -0.4267],
        [ 2.3455, -0.0341, -0.6838,  0.3348, -1.0165],
        [ 0.1294, -0.6206,  0.1526,  0.0235,  0.9148],
        [ 0.5069, -0.3140, -0.8618,  0.4178,  1.2679],
        [ 0.9608, -0.7316, -0.8575,  1.7397,  0.3248]])